import type { NotificationEventType } from '../enums/index.js'
import { NotificationDomainError } from './errors.js'

/**
 * A persisted notification event (SPEC/20-feature-notifications.md). One row is written per
 * recipient per trigger. Outbound email delivery is explicitly deferred outside MVP - these rows
 * are recorded for later processing and are never delivered here.
 *
 * No `Auditable` - `notification_events` carries no `updated_at_utc`/`*_by_user_id` columns,
 * matching `packages/domain/src/upvotes`.
 */
export type NotificationEvent = {
  readonly id: string
  readonly eventType: NotificationEventType
  readonly organizationId: string
  readonly boardId: string
  readonly ideaId: string
  readonly ideaTitle: string
  readonly actorUserId: string
  readonly recipientUserId: string
  readonly link: string
  readonly occurredAtUtc: Date
}

export type CreateNotificationEventProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md). */
  readonly id: string
  readonly eventType: NotificationEventType
  readonly organizationId: string
  readonly boardId: string
  readonly ideaId: string
  readonly ideaTitle: string
  readonly actorUserId: string
  readonly recipientUserId: string
  readonly occurredAtUtc: Date
}

/**
 * The canonical idea link persisted on every notification event.
 *
 * `/ideas/{ideaId}` per SPEC/20-feature-notifications.md "Canonical Idea Link" (current), which
 * explicitly supersedes both the earlier board-scoped route and the .NET code's
 * `/ideas/{ideaId}/edit` (a still-earlier interim route the C# comment never caught up to). No
 * read/query endpoint exposes this field in MVP, so no golden-corpus fixture observes it either
 * way; the spec is followed as the more current, canonical source.
 */
export function buildIdeaLink(ideaId: string): string {
  return `/ideas/${ideaId}`
}

function assertRequiredId(field: string, value: string, message: string): string {
  if (!value || value.trim().length === 0) {
    throw new NotificationDomainError(field, message)
  }
  return value
}

export function createNotificationEvent(props: CreateNotificationEventProps): NotificationEvent {
  const organizationId = assertRequiredId(
    'organizationId',
    props.organizationId,
    'Organization id is required.',
  )
  const ideaId = assertRequiredId('ideaId', props.ideaId, 'Idea id is required.')
  const recipientUserId = assertRequiredId(
    'recipientUserId',
    props.recipientUserId,
    'Recipient id is required.',
  )

  return {
    id: props.id,
    eventType: props.eventType,
    organizationId,
    boardId: props.boardId,
    ideaId,
    ideaTitle: props.ideaTitle ?? '',
    actorUserId: props.actorUserId,
    recipientUserId,
    link: buildIdeaLink(ideaId),
    occurredAtUtc: props.occurredAtUtc,
  }
}
