// <auto-generated />
using System;
using Collega.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collega.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CollegaDbContext))]
    [Migration("20260807145502_AddAuthEntities")]
    partial class AddAuthEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Collega.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_occurred_at_utc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_audit_events_organization_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Collega.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_invite_code");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Collega.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_until_utc");

                    b.Property<DateTime?>("LockoutWindowStartUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_window_start_utc");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TemporaryPasswordExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("temporary_password_expires_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Collega.Domain.Users.User", b =>
                {
                    b.HasOne("Collega.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
