// Organization-scoped Idea Type option (SPEC/30-Contracts.md "Idea Field Option Contracts",
// SPEC/20-feature-idea-type-fields.md). Options are ordered by `sortOrder`; the first active
// option is the default for new ideas. Soft-deletion preserves existing idea references (their
// prior label stays readable with an archived indicator). Every organization must retain at least
// one active Idea Type.
//
// A type also owns an optional badge appearance (`colorHex` + `icon`) and a `fieldMode` that
// governs which User-Defined Fields its ideas resolve to - see `idea-type-field-resolver.ts`.
//
// Modelled as plain immutable data plus transition functions, per `packages/domain/src/common`.

import { type Auditable, markCreated, markUpdated } from '../common/index.js'
import { IdeaTypeFieldMode } from '../enums/index.js'

export const IDEA_TYPE_NAME_MAX_LENGTH = 100

/** `#RRGGBB` is exactly seven characters, so this is a fixed width rather than a ceiling. */
export const IDEA_TYPE_COLOR_HEX_LENGTH = 7

export const IDEA_TYPE_ICON_MAX_LENGTH = 64

/** Every organization must keep at least this many active options. */
export const MINIMUM_ACTIVE_IDEA_TYPES_PER_ORGANIZATION = 1

const HEX_COLOR_PATTERN = /^#[0-9a-fA-F]{6}$/

/**
 * Raised when a caller asks this module to put an `IdeaType` into an invalid state. Carries the
 * field the violation belongs to, mirroring `IdeaDomainError`/`StatusInvariantError`, so the
 * Application layer can translate it into a field-keyed `ValidationError` instead of letting a
 * bare `Error` become a 500 (SPEC/decisions.md 2026-09-06 "Wave B conventions"). In practice every
 * one of these is a defensive backstop: `IdeaTypeService` validates name/color/selection itself
 * before calling in, exactly mirroring how the .NET `IdeaFieldService` never wrapped these calls -
 * its own `ArgumentException`s were never meant to be reached.
 */
export class IdeaTypeDomainError extends Error {
  readonly field: string

  constructor(field: string, message: string) {
    super(message)
    this.name = 'IdeaTypeDomainError'
    this.field = field
  }
}

/**
 * The association between an `IdeaType` and one of the organization's User-Defined Field
 * definitions (SPEC/20-feature-idea-type-fields.md). Per-type ordering and required-ness live
 * here so a field can be mandatory on one type and absent from another while the field pool stays
 * shared. At most one entry per `fieldDefinitionId` within a type.
 */
export type IdeaTypeField = {
  readonly id: string
  readonly ideaTypeId: string
  readonly fieldDefinitionId: string
  /** Order of this field within its owning type (independent of the field's global order). */
  readonly displayOrder: number
  /** Required within this type; overrides the field definition's global default. */
  readonly isRequired: boolean
}

/**
 * One entry in a replace-the-selection request passed to `setIdeaTypeFieldSelection`. `id` is
 * generated by the Application layer with `randomUUID()` - the domain never generates one
 * (SPEC/decisions.md 2026-09-06). The Application layer also validates that `fieldDefinitionId`
 * is an active field in the type's organization before constructing this.
 */
export type IdeaTypeFieldInput = {
  readonly id: string
  readonly fieldDefinitionId: string
  readonly displayOrder: number
  readonly isRequired: boolean
}

export type IdeaType = Auditable & {
  readonly id: string
  readonly organizationId: string
  readonly name: string
  readonly sortOrder: number
  readonly isDeleted: boolean
  /** Badge color as `#RRGGBB`; null falls back to a neutral badge. */
  readonly colorHex: string | null
  /** Short badge token (emoji or icon key); null renders no icon. */
  readonly icon: string | null
  /** Which fields this type's ideas resolve to - see `idea-type-field-resolver.ts`. */
  readonly fieldMode: IdeaTypeFieldMode
  /** The type's curated field selection; only consulted when `fieldMode` is `Curated`. */
  readonly fields: readonly IdeaTypeField[]
}

function normalizeName(name: string): string {
  const trimmed = (name ?? '').trim()
  if (trimmed.length === 0) {
    throw new IdeaTypeDomainError('name', 'Name is required.')
  }
  return trimmed
}

export function createIdeaType(params: {
  readonly id: string
  readonly organizationId: string
  readonly name: string
  readonly sortOrder: number
  readonly nowUtc: Date
  readonly actorUserId: string | null
}): IdeaType {
  if (params.organizationId.trim().length === 0) {
    throw new IdeaTypeDomainError('organizationId', 'Organization id is required.')
  }

  return {
    id: params.id,
    organizationId: params.organizationId,
    name: normalizeName(params.name),
    sortOrder: params.sortOrder,
    isDeleted: false,
    colorHex: null,
    icon: null,
    fieldMode: IdeaTypeFieldMode.AllActiveFields,
    fields: [],
    ...markCreated(params.nowUtc, params.actorUserId),
  }
}

function ensureNotDeleted(ideaType: IdeaType): void {
  if (ideaType.isDeleted) {
    throw new IdeaTypeDomainError('ideaType', 'A deleted Idea Type cannot be updated.')
  }
}

export function updateIdeaType(
  ideaType: IdeaType,
  params: { readonly name: string; readonly sortOrder: number },
  nowUtc: Date,
  actorUserId: string | null,
): IdeaType {
  ensureNotDeleted(ideaType)
  return markUpdated(
    { ...ideaType, name: normalizeName(params.name), sortOrder: params.sortOrder },
    nowUtc,
    actorUserId,
  )
}

/** Sets only the catalog sort order, leaving name and appearance untouched. */
export function setIdeaTypeSortOrder(
  ideaType: IdeaType,
  sortOrder: number,
  nowUtc: Date,
  actorUserId: string | null,
): IdeaType {
  return markUpdated({ ...ideaType, sortOrder }, nowUtc, actorUserId)
}

/** Soft-deletes the option so existing idea references stay valid. Idempotent. */
export function softDeleteIdeaType(
  ideaType: IdeaType,
  nowUtc: Date,
  actorUserId: string | null,
): IdeaType {
  if (ideaType.isDeleted) {
    return ideaType
  }
  return markUpdated({ ...ideaType, isDeleted: true }, nowUtc, actorUserId)
}

/**
 * Sets or clears the badge appearance. `colorHex` must be `#RRGGBB` when non-null; either
 * argument may be null/blank to clear that part of the badge.
 */
export function setIdeaTypeAppearance(
  ideaType: IdeaType,
  colorHex: string | null,
  icon: string | null,
  nowUtc: Date,
  actorUserId: string | null,
): IdeaType {
  ensureNotDeleted(ideaType)

  const normalizedColor = colorHex && colorHex.trim().length > 0 ? colorHex.trim() : null
  if (normalizedColor !== null && !HEX_COLOR_PATTERN.test(normalizedColor)) {
    throw new IdeaTypeDomainError('colorHex', 'Color must be a valid #RRGGBB hex color.')
  }

  const normalizedIcon = icon && icon.trim().length > 0 ? icon.trim() : null
  if (normalizedIcon !== null && normalizedIcon.length > IDEA_TYPE_ICON_MAX_LENGTH) {
    throw new IdeaTypeDomainError(
      'icon',
      `Icon must be ${IDEA_TYPE_ICON_MAX_LENGTH} characters or fewer.`,
    )
  }

  return markUpdated(
    { ...ideaType, colorHex: normalizedColor, icon: normalizedIcon },
    nowUtc,
    actorUserId,
  )
}

/**
 * Replaces the type's field selection and switches it to `Curated`. A field appears at most once;
 * duplicates are rejected. An empty list is equivalent to `clearIdeaTypeFieldSelection`. Callers
 * validate that each field is active and in-org first.
 */
export function setIdeaTypeFieldSelection(
  ideaType: IdeaType,
  links: readonly IdeaTypeFieldInput[],
  nowUtc: Date,
  actorUserId: string | null,
): IdeaType {
  ensureNotDeleted(ideaType)

  if (links.length === 0) {
    return clearIdeaTypeFieldSelection(ideaType, nowUtc, actorUserId)
  }

  const seen = new Set<string>()
  const replacement: IdeaTypeField[] = []
  for (const link of links) {
    if (seen.has(link.fieldDefinitionId)) {
      throw new IdeaTypeDomainError(
        'fields',
        `Field '${link.fieldDefinitionId}' is selected more than once.`,
      )
    }
    seen.add(link.fieldDefinitionId)
    replacement.push({
      id: link.id,
      ideaTypeId: ideaType.id,
      fieldDefinitionId: link.fieldDefinitionId,
      displayOrder: link.displayOrder,
      isRequired: link.isRequired,
    })
  }

  return markUpdated(
    { ...ideaType, fields: replacement, fieldMode: IdeaTypeFieldMode.Curated },
    nowUtc,
    actorUserId,
  )
}

/** Empties the field selection and returns the type to `AllActiveFields`. */
export function clearIdeaTypeFieldSelection(
  ideaType: IdeaType,
  nowUtc: Date,
  actorUserId: string | null,
): IdeaType {
  ensureNotDeleted(ideaType)
  return markUpdated(
    { ...ideaType, fields: [], fieldMode: IdeaTypeFieldMode.AllActiveFields },
    nowUtc,
    actorUserId,
  )
}
