import type { Auditable } from '../common/index.js'
import { markCreated } from '../common/index.js'
import { TagDomainError } from './errors.js'

/** Mirrors .NET's `Tag.NameMaxLength`. Not enforced here - the .NET domain never checked it in
 * `Tag.Create` either; the 10-tags-per-idea and 100-character caps are enforced by the caller
 * (Ideas' `resolveTags`, SPEC/20-feature-ideas-and-engagement.md "Tags" #3/#8) before a name ever
 * reaches this factory. Kept as a named constant for that caller to reference. */
export const NAME_MAX_LENGTH = 100

/**
 * A reusable, organization-scoped tag (SPEC/20-feature-ideas-and-engagement.md "Tags"). Trimmed,
 * compared case-insensitively via `normalizedName`, and unique within an organization (the
 * database's `ux_tags_organization_id_normalized_name` index is the actual guarantee; concurrent
 * creation of the same normalized name is merged into one tag by the Application layer's
 * `getOrCreate`).
 *
 * Immutable data, not a class - consistent with `packages/domain/src/ideas`.
 */
export type Tag = Auditable & {
  readonly id: string
  readonly organizationId: string
  /** Display value as first entered (trimmed). */
  readonly name: string
  /** Lower-cased, trimmed form used for uniqueness and prefix matching. */
  readonly normalizedName: string
}

export type CreateTagProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md). */
  readonly id: string
  readonly organizationId: string
  readonly name: string
  readonly nowUtc: Date
  readonly actorUserId: string | null
}

/** Trims surrounding whitespace and lower-cases for case-insensitive comparison. */
export function normalizeTagName(name: string | null | undefined): string {
  return (name ?? '').trim().toLowerCase()
}

export function createTag(props: CreateTagProps): Tag {
  if (!props.organizationId || props.organizationId.trim().length === 0) {
    throw new TagDomainError('organizationId', 'Organization id is required.')
  }

  const normalizedName = normalizeTagName(props.name)
  if (normalizedName.length === 0) {
    throw new TagDomainError('name', 'Tag name is required.')
  }

  return {
    id: props.id,
    organizationId: props.organizationId,
    name: props.name.trim(),
    normalizedName,
    ...markCreated(props.nowUtc, props.actorUserId),
  }
}
