import type { Auditable } from '../common/index.js'
import { markCreated, markUpdated } from '../common/index.js'
import { TagDomainError } from './errors.js'

/** Mirrors .NET's `Tag.NameMaxLength`. Inline creation while tagging an idea checks it first, keyed
 * `tagNames` (Ideas' `resolveTags`); `createTag` and `updateTag` enforce it for Settings → Tags. */
export const NAME_MAX_LENGTH = 100

/**
 * The palette a new tag's random colour is drawn from, in the order
 * SPEC/20-feature-ideas-and-engagement.md Tags rule 9 lists it. The order is load-bearing: the
 * `tags.color` backfill and the demo seed both index it by the first byte of the MD5 digest of the
 * normalized name, modulo 10.
 */
export const TAG_COLOR_PALETTE = [
  '#E5484D',
  '#F5A524',
  '#3FB86B',
  '#2F9E8F',
  '#5CC8E0',
  '#6B9BF2',
  '#B08CF5',
  '#E879A6',
  '#A87B2F',
  '#94A3B8',
] as const

const HEX_COLOR = /^#[0-9a-fA-F]{6}$/

/**
 * A reusable, organization-scoped tag (SPEC/20-feature-ideas-and-engagement.md "Tags"). Trimmed,
 * compared case-insensitively via `normalizedName`, and unique within an organization (the
 * database's `ux_tags_organization_id_normalized_name` index is the actual guarantee; concurrent
 * creation of the same normalized name is merged into one tag by the Application layer's
 * `getOrCreate`).
 *
 * Immutable data, not a class - consistent with `packages/domain/src/ideas`.
 */
export type Tag = Auditable & {
  readonly id: string
  readonly organizationId: string
  /** Display value as first entered (trimmed). */
  readonly name: string
  /** Lower-cased, trimmed form used for uniqueness and prefix matching. */
  readonly normalizedName: string
  /** `#RRGGBB`, upper case (Tags rule 9). */
  readonly color: string
}

export type CreateTagProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md). */
  readonly id: string
  readonly organizationId: string
  readonly name: string
  readonly color: string
  readonly nowUtc: Date
  readonly actorUserId: string | null
}

/** Trims surrounding whitespace and lower-cases for case-insensitive comparison. */
export function normalizeTagName(name: string | null | undefined): string {
  return (name ?? '').trim().toLowerCase()
}

/** Any `#RRGGBB`, returned upper case; anything else is refused on `color`. */
export function normalizeTagColor(color: string): string {
  if (!HEX_COLOR.test(color)) {
    throw new TagDomainError('color', 'Color must be a valid #RRGGBB color.')
  }
  return color.toUpperCase()
}

/** The trimmed display name, refused on `name` when blank or over `NAME_MAX_LENGTH`. */
export function validateTagName(name: string | null | undefined): string {
  const trimmed = (name ?? '').trim()
  if (trimmed.length === 0) {
    throw new TagDomainError('name', 'Tag name is required.')
  }
  if (trimmed.length > NAME_MAX_LENGTH) {
    throw new TagDomainError('name', `Tag must be ${NAME_MAX_LENGTH} characters or fewer.`)
  }
  return trimmed
}

/** The palette colour at `index`, which the caller draws from its random source. */
export function paletteColorAt(index: number): string {
  const color = TAG_COLOR_PALETTE[index]
  if (color === undefined) {
    throw new RangeError(`Palette index ${index} is outside 0-${TAG_COLOR_PALETTE.length - 1}.`)
  }
  return color
}

export function createTag(props: CreateTagProps): Tag {
  if (!props.organizationId || props.organizationId.trim().length === 0) {
    throw new TagDomainError('organizationId', 'Organization id is required.')
  }

  const name = validateTagName(props.name)
  const color = normalizeTagColor(props.color)

  return {
    id: props.id,
    organizationId: props.organizationId,
    name,
    normalizedName: normalizeTagName(name),
    color,
    ...markCreated(props.nowUtc, props.actorUserId),
  }
}

/**
 * Renames and/or recolours a tag (Tags rule 14). `color` null keeps the stored one. Uniqueness of
 * the new name against the organization's other tags is the Application layer's check.
 */
export function updateTag(
  tag: Tag,
  changes: { readonly name: string; readonly color: string | null },
  nowUtc: Date,
  actorUserId: string | null,
): Tag {
  const name = validateTagName(changes.name)
  const color = changes.color === null ? tag.color : normalizeTagColor(changes.color)
  return markUpdated(
    { ...tag, name, normalizedName: normalizeTagName(name), color },
    nowUtc,
    actorUserId,
  )
}
