import type { Auditable } from '../common/index.js'
import { markCreated, markUpdated } from '../common/index.js'
import type { EffortLevel, Priority } from '../enums/index.js'
import { DeliveryStatus, IdeaPhase } from '../enums/index.js'
import { IdeaDomainError, IdeaPhaseConflictError } from './errors.js'

export const TITLE_MAX_LENGTH = 150
export const DESCRIPTION_MAX_LENGTH = 4000
export const MAX_ASSIGNEES = 5
export const MAX_TAGS = 10

/** A single User-Defined Field value submitted for an idea. A null/blank value clears it. */
export type IdeaFieldValueInput = {
  readonly fieldDefinitionId: string
  readonly value: string | null
}

/** A stored (non-empty) User-Defined Field value on an idea. */
export type IdeaFieldValueRecord = {
  readonly fieldDefinitionId: string
  readonly value: string
}

/**
 * An idea on a board (SPEC/20-feature-ideas-and-engagement.md "Idea Rules"). Owns its assignee
 * and mention associations directly. Tags, idea type, business impact and custom-field values are
 * referenced by plain id only: Tags (`idea_tags`) belong to B4, and Idea Type / Business Impact /
 * User-Defined Fields (`idea_types`, `business_impacts`, `field_definitions`, `idea_field_values`)
 * belong to B5. Status is derived from the swimlane the idea sits in; deletion is a soft delete
 * that preserves the row and its audit history (rule #11).
 *
 * Immutable data plus the transition functions below, per `packages/domain/src/common` - not a
 * class, so `markCreated`/`markUpdated` apply directly.
 *
 * `Idea.OutcomeId` (SPEC/decisions.md 2026-09-02, single-parent Outcome<->Issue linkage: a nullable
 * FK, never a join table) belongs to a later slice - the frozen `ideas` table for this slice
 * carries no `outcome_id` column ("Nothing in Slice 1 depended on this"), so it is deliberately not
 * modeled here.
 *
 * The delivery facets below are Issues-and-Delivery Slice 1
 * (SPEC/20-feature-issues-and-delivery.md). An Issue is not a second entity: it is this same idea
 * with `phase === Delivery`. That is the point of the feature - promotion copies nothing, so the
 * proposer, upvotes, business impact and the whole comment debate arrive in the sprint intact.
 */
export type Idea = Auditable & {
  readonly id: string
  readonly organizationId: string
  readonly boardId: string
  /**
   * The ideation status. Frozen at its last Discovery value on promotion and never cleared:
   * ideation `Complete` and delivery `Complete` are distinct terminal states, and an item in
   * Delivery keeps both.
   */
  readonly statusId: string
  readonly title: string
  readonly description: string
  readonly priority: Priority
  readonly ideaTypeId: string
  readonly businessImpactId: string
  readonly dueDate: string | null
  readonly authorUserId: string
  readonly isDeleted: boolean
  readonly assigneeUserIds: readonly string[]
  readonly tagIds: readonly string[]
  readonly mentionedUserIds: readonly string[]
  readonly fieldValues: readonly IdeaFieldValueRecord[]
  /** `Discovery` (ideation board) or `Delivery` (sprint board). Every existing idea is Discovery. */
  readonly phase: IdeaPhase
  /** Optional while in Discovery; required at the promotion gate, and retained after a return. */
  readonly effort: EffortLevel | null
  /** Null in Discovery; `Pending` from promotion onward. */
  readonly deliveryStatus: DeliveryStatus | null
  /** Null means the delivery backlog. Only meaningful in Delivery. */
  readonly sprintId: string | null
  /** Promotion snapshot: who committed to this work, when, and how much support it had then. */
  readonly promotedAtUtc: Date | null
  readonly promotedByUserId: string | null
  readonly upvoteCountAtPromotion: number | null
}

export type CreateIdeaProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md). */
  readonly id: string
  readonly organizationId: string
  readonly boardId: string
  readonly statusId: string
  readonly title: string
  readonly description: string
  readonly priority: Priority
  readonly ideaTypeId: string
  readonly businessImpactId: string
  readonly dueDate: string | null
  /** The acting user, recorded as author AND as created/updated-by (SPEC/20-feature-view-as.md
   * rule 15 - authorship records the TARGET, never rewritten to the real administrator). */
  readonly authorUserId: string
  readonly assigneeUserIds: readonly string[]
  readonly tagIds: readonly string[]
  readonly mentionedUserIds: readonly string[]
  readonly nowUtc: Date
}

function assertRequiredId(field: string, value: string, message: string): string {
  if (!value || value.trim().length === 0) {
    throw new IdeaDomainError(field, message)
  }
  return value
}

function normalizeTitle(title: string): string {
  const trimmed = (title ?? '').trim()
  if (trimmed.length === 0) {
    throw new IdeaDomainError('title', 'Title is required.')
  }
  if (trimmed.length > TITLE_MAX_LENGTH) {
    throw new IdeaDomainError('title', `Title must be ${TITLE_MAX_LENGTH} characters or fewer.`)
  }
  return trimmed
}

function normalizeDescription(description: string): string {
  const trimmed = (description ?? '').trim()
  if (trimmed.length === 0) {
    throw new IdeaDomainError('description', 'Description is required.')
  }
  if (trimmed.length > DESCRIPTION_MAX_LENGTH) {
    throw new IdeaDomainError(
      'description',
      `Description must be ${DESCRIPTION_MAX_LENGTH} characters or fewer.`,
    )
  }
  return trimmed
}

function distinctIds(ids: readonly string[] | null | undefined): string[] {
  if (!ids) {
    return []
  }
  const seen = new Set<string>()
  const result: string[] = []
  for (const id of ids) {
    if (!id || seen.has(id)) {
      continue
    }
    seen.add(id)
    result.push(id)
  }
  return result
}

function normalizeAssignees(assigneeUserIds: readonly string[]): string[] {
  const distinct = distinctIds(assigneeUserIds)
  if (distinct.length > MAX_ASSIGNEES) {
    throw new IdeaDomainError(
      'assigneeUserIds',
      `An idea can have at most ${MAX_ASSIGNEES} assignees.`,
    )
  }
  return distinct
}

function normalizeTags(tagIds: readonly string[]): string[] {
  const distinct = distinctIds(tagIds)
  if (distinct.length > MAX_TAGS) {
    throw new IdeaDomainError('tagIds', `An idea can have at most ${MAX_TAGS} tags.`)
  }
  return distinct
}

export function createIdea(props: CreateIdeaProps): Idea {
  const id = assertRequiredId('id', props.id, 'Idea id is required.')
  const organizationId = assertRequiredId(
    'organizationId',
    props.organizationId,
    'Organization id is required.',
  )
  const boardId = assertRequiredId('boardId', props.boardId, 'Board id is required.')
  const statusId = assertRequiredId('statusId', props.statusId, 'Status id is required.')
  const authorUserId = assertRequiredId(
    'authorUserId',
    props.authorUserId,
    'Author id is required.',
  )
  const ideaTypeId = assertRequiredId('ideaTypeId', props.ideaTypeId, 'Idea Type is required.')
  const businessImpactId = assertRequiredId(
    'businessImpactId',
    props.businessImpactId,
    'Business Impact is required.',
  )

  return {
    id,
    organizationId,
    boardId,
    statusId,
    title: normalizeTitle(props.title),
    description: normalizeDescription(props.description),
    priority: props.priority,
    ideaTypeId,
    businessImpactId,
    dueDate: props.dueDate,
    authorUserId,
    isDeleted: false,
    assigneeUserIds: normalizeAssignees(props.assigneeUserIds),
    tagIds: normalizeTags(props.tagIds),
    mentionedUserIds: distinctIds(props.mentionedUserIds),
    fieldValues: [],
    phase: IdeaPhase.Discovery,
    effort: null,
    deliveryStatus: null,
    sprintId: null,
    promotedAtUtc: null,
    promotedByUserId: null,
    upvoteCountAtPromotion: null,
    // Rule 15: authorship records the TARGET (the acting user), never rewritten to the real
    // administrator - content created through View As genuinely belongs to that organization.
    ...markCreated(props.nowUtc, authorUserId),
  }
}

/**
 * Updates the core editable fields (rule #6 keeps this available in the Complete status).
 * Assignees, tags and mentions are replaced through their own functions. Idea Type is immutable
 * here (SPEC/20-feature-idea-type-fields.md) - only `reassignIdeaType` may change it.
 */
export function updateIdeaContent(
  idea: Idea,
  input: {
    readonly title: string
    readonly description: string
    readonly priority: Priority
    readonly businessImpactId: string
    readonly dueDate: string | null
  },
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  return markUpdated(
    {
      ...idea,
      title: normalizeTitle(input.title),
      description: normalizeDescription(input.description),
      priority: input.priority,
      businessImpactId: assertRequiredId(
        'businessImpactId',
        input.businessImpactId,
        'Business Impact is required.',
      ),
      dueDate: input.dueDate,
    },
    nowUtc,
    actorUserId,
  )
}

/** Admin-only reassignment of the idea's type - the only path that mutates `ideaTypeId` after
 * creation (SPEC/20-feature-idea-type-fields.md). Field-value reconciliation against the new
 * type's resolved set is the caller's responsibility. */
export function reassignIdeaType(
  idea: Idea,
  ideaTypeId: string,
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  return markUpdated(
    { ...idea, ideaTypeId: assertRequiredId('ideaTypeId', ideaTypeId, 'Idea Type is required.') },
    nowUtc,
    actorUserId,
  )
}

export function changeIdeaStatus(
  idea: Idea,
  statusId: string,
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  return markUpdated(
    { ...idea, statusId: assertRequiredId('statusId', statusId, 'Status id is required.') },
    nowUtc,
    actorUserId,
  )
}

/**
 * Sets or clears the optional Discovery-phase effort estimate.
 *
 * Discovery only, deliberately. In Delivery, `effort` is no longer a working estimate - it is half
 * of what the promotion gate recorded, sitting beside `promotedByUserId` and
 * `upvoteCountAtPromotion`, and a later edit through the ordinary update path would quietly rewrite
 * the answer to "how big did we think this was when we committed to it". Re-estimating a live Issue
 * is not modelled in this slice; the gate is where an effort is chosen.
 *
 * A `null` clears it, matching `dueDate` - the only other optional scalar on the edit path.
 */
export function setIdeaEffort(
  idea: Idea,
  effort: EffortLevel | null,
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  if (idea.phase !== IdeaPhase.Discovery) {
    throw new IdeaDomainError(
      'effort',
      'Effort is recorded at the promotion gate and cannot be changed on an issue.',
    )
  }
  return markUpdated({ ...idea, effort }, nowUtc, actorUserId)
}

/**
 * The promotion gate: flips this idea into Delivery, where it is called an Issue
 * (SPEC/20-feature-issues-and-delivery.md "Domain Model"). An explicit decision with an actor and
 * a timestamp - never a side effect of reaching some ideation status, which is the overloading the
 * feature exists to avoid.
 *
 * `effort` is required here even though it is optional in Discovery: committing to work without
 * saying roughly how big it is is the thing the gate is for.
 *
 * Note what is NOT touched: `statusId`. The ideation status freezes at its last Discovery value
 * and is kept for provenance, because ideation `Complete` ("the discussion is finished") and
 * delivery `Complete` ("the work is built") are different facts and losing either one is losing
 * history.
 */
export function promoteIdeaToIssue(
  idea: Idea,
  input: {
    readonly effort: EffortLevel
    /** `null` promotes straight to the delivery backlog. */
    readonly sprintId: string | null
    /** The idea's upvote count right now, frozen as the support-at-commitment snapshot. */
    readonly currentUpvoteCount: number
  },
  nowUtc: Date,
  actorUserId: string,
): Idea {
  // Re-promoting is rejected rather than treated as an update: a second promotion would overwrite
  // the snapshot of who committed to this work and how much support it had at the time, which is
  // the one piece of provenance this feature genuinely stores rather than inherits.
  if (idea.phase === IdeaPhase.Delivery) {
    throw new IdeaPhaseConflictError('This idea is already in delivery.')
  }
  const promotedByUserId = assertRequiredId('actorUserId', actorUserId, 'Actor id is required.')

  return markUpdated(
    {
      ...idea,
      phase: IdeaPhase.Delivery,
      deliveryStatus: DeliveryStatus.Pending,
      effort: input.effort,
      sprintId: input.sprintId,
      promotedAtUtc: nowUtc,
      promotedByUserId,
      upvoteCountAtPromotion: input.currentUpvoteCount,
    },
    nowUtc,
    actorUserId,
  )
}

/**
 * Recovers a mis-promotion (admin-only, per the permissions table). Clears the two facts that only
 * make sense in Delivery - the sprint membership and the delivery status - and deliberately
 * RETAINS `effort` and the promotion snapshot.
 *
 * Retaining them is what keeps both the audit trail and a later re-promote coherent: the snapshot
 * records that this item *was* committed to once, which is history and not a mistake to erase, and
 * a re-promote then has the earlier effort estimate to offer as a default. Tasks are retained for
 * the same reason (they hang off the idea, so nothing here has to do it).
 *
 * Rejected from Discovery rather than treated as a no-op: succeeding silently would write an
 * `IssueReturnedToDiscovery` audit event for an item that was never promoted.
 */
export function returnIdeaToDiscovery(idea: Idea, nowUtc: Date, actorUserId: string | null): Idea {
  if (idea.phase !== IdeaPhase.Delivery) {
    throw new IdeaPhaseConflictError('This idea is not in delivery.')
  }

  return markUpdated(
    { ...idea, phase: IdeaPhase.Discovery, deliveryStatus: null, sprintId: null },
    nowUtc,
    actorUserId,
  )
}

/**
 * Moves an Issue between the five fixed delivery statuses - the sprint board's swimlanes.
 *
 * Any status may follow any other: the board is a kanban and dragging backwards is a normal
 * correction, not an invariant violation. Outstanding tasks never block `Complete` either - the UI
 * warns, the domain permits, because enforcing "all tasks done" would turn the checklist into a
 * gate, which is exactly the ceremony this feature refuses.
 */
export function changeIdeaDeliveryStatus(
  idea: Idea,
  deliveryStatus: DeliveryStatus,
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  requireDeliveryPhase(idea, 'deliveryStatus', 'A delivery status applies only to a promoted idea.')
  return markUpdated({ ...idea, deliveryStatus }, nowUtc, actorUserId)
}

/** Pulls an Issue into a sprint, or back to the delivery backlog with `null`. */
export function assignIdeaToSprint(
  idea: Idea,
  sprintId: string | null,
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  requireDeliveryPhase(idea, 'sprintId', 'Only a promoted idea can be assigned to a sprint.')
  return markUpdated({ ...idea, sprintId }, nowUtc, actorUserId)
}

/**
 * The two mutations above are meaningless on a Discovery item, and the contract answers `400`
 * there (not the `409` a wrong-phase promotion gets) - so this raises the field-keyed
 * `IdeaDomainError` the Application layer already maps to a 400.
 */
function requireDeliveryPhase(idea: Idea, field: string, message: string): void {
  if (idea.phase !== IdeaPhase.Delivery) {
    throw new IdeaDomainError(field, message)
  }
}

export function replaceIdeaAssignees(
  idea: Idea,
  assigneeUserIds: readonly string[],
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  return markUpdated(
    { ...idea, assigneeUserIds: normalizeAssignees(assigneeUserIds) },
    nowUtc,
    actorUserId,
  )
}

export function replaceIdeaTags(
  idea: Idea,
  tagIds: readonly string[],
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  return markUpdated({ ...idea, tagIds: normalizeTags(tagIds) }, nowUtc, actorUserId)
}

export function replaceIdeaMentions(
  idea: Idea,
  mentionedUserIds: readonly string[],
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  return markUpdated(
    { ...idea, mentionedUserIds: distinctIds(mentionedUserIds) },
    nowUtc,
    actorUserId,
  )
}

/**
 * Reconciles this idea's field values to the submitted set (authoritative): a field with a
 * null/blank value is cleared, a changed value overwrites in place, a new value is added, and
 * unchanged values are left untouched. Values must already be validated/serialized by the
 * Application layer (delegated to B5's field-value port).
 *
 * @param reconciledFieldDefinitionIds The field definitions this reconcile is authoritative
 * over - the caller's active/effective set for the idea's type. Only values for these fields
 * may be cleared; values for out-of-scope definitions (e.g. removed from a curated type, or
 * archived on reassignment) are preserved untouched so historical data is not lost
 * (SPEC/20-feature-user-defined-fields.md).
 */
export function replaceIdeaFieldValues(
  idea: Idea,
  fieldValues: readonly IdeaFieldValueInput[],
  reconciledFieldDefinitionIds: readonly string[],
  nowUtc: Date,
  actorUserId: string | null,
): Idea {
  const scoped = new Set(reconciledFieldDefinitionIds)

  // Last submission wins if a field id is repeated.
  const desired = new Map<string, string | null>()
  for (const input of fieldValues) {
    if (!input.fieldDefinitionId) {
      continue
    }
    const blank = input.value === null || input.value.trim().length === 0
    desired.set(input.fieldDefinitionId, blank ? null : input.value)
  }

  const next = new Map(idea.fieldValues.map((v) => [v.fieldDefinitionId, v.value]))
  // Only clear values for in-scope definitions; leave out-of-scope (archived) values in place.
  for (const fieldDefinitionId of Array.from(next.keys())) {
    if (!scoped.has(fieldDefinitionId)) {
      continue
    }
    const desiredValue = desired.get(fieldDefinitionId)
    if (desiredValue === undefined || desiredValue === null) {
      next.delete(fieldDefinitionId)
    }
  }

  for (const [fieldDefinitionId, value] of desired) {
    if (value === null) {
      continue
    }
    next.set(fieldDefinitionId, value)
  }

  const fieldValueRecords: readonly IdeaFieldValueRecord[] = Array.from(
    next,
    ([fieldDefinitionId, value]) => ({ fieldDefinitionId, value }),
  )
  return markUpdated({ ...idea, fieldValues: fieldValueRecords }, nowUtc, actorUserId)
}

export function softDeleteIdea(idea: Idea, nowUtc: Date, actorUserId: string | null): Idea {
  return markUpdated({ ...idea, isDeleted: true }, nowUtc, actorUserId)
}
