// Organization-owned fieldset: a named, ordered group of the organization's field definitions that
// idea types attach as a live reference (SPEC/20-feature-idea-type-fields.md "Effective-field
// resolution", SPEC/contracts/fieldsets.md). Editing a fieldset changes every type using it, so a
// type stores only the attachment, never a copy of the members.
//
// Plain immutable data plus transition functions, per `packages/domain/src/common`.

import { type Auditable, markCreated, markUpdated } from '../common/index.js'
import {
  FIELD_DESCRIPTION_MAX_LENGTH,
  FIELD_NAME_MAX_LENGTH,
  normalizeFieldName,
} from '../fields/index.js'

export const FIELDSET_NAME_MAX_LENGTH = FIELD_NAME_MAX_LENGTH
export const FIELDSET_DESCRIPTION_MAX_LENGTH = FIELD_DESCRIPTION_MAX_LENGTH

/** Keyed on the offending property so the application layer can raise a field-keyed `400`. A
 * sibling of the other per-feature domain errors rather than a subclass of any of them. */
export class FieldsetDomainError extends Error {
  readonly field: string

  constructor(field: string, message: string) {
    super(message)
    this.name = 'FieldsetDomainError'
    this.field = field
  }
}

/** One member of a fieldset. At most one entry per `fieldDefinitionId` within a fieldset. */
export type FieldsetField = {
  readonly id: string
  readonly fieldsetId: string
  readonly fieldDefinitionId: string
  readonly displayOrder: number
}

/** Replace-the-members entry; `id` is generated by the application layer, never here. */
export type FieldsetFieldInput = {
  readonly id: string
  readonly fieldDefinitionId: string
  readonly displayOrder: number
}

export type Fieldset = Auditable & {
  readonly id: string
  readonly organizationId: string
  readonly name: string
  /** Trimmed, lower-cased `name`; backs the unique `(organization_id, normalized_name)` index. */
  readonly normalizedName: string
  readonly description: string | null
  readonly displayOrder: number
  readonly fields: readonly FieldsetField[]
}

function normalizeName(name: string): string {
  const trimmed = (name ?? '').trim()
  if (trimmed.length === 0) {
    throw new FieldsetDomainError('name', 'Name is required.')
  }
  if (trimmed.length > FIELDSET_NAME_MAX_LENGTH) {
    throw new FieldsetDomainError(
      'name',
      `Name must be ${FIELDSET_NAME_MAX_LENGTH} characters or fewer.`,
    )
  }
  return trimmed
}

function normalizeDescription(description: string | null): string | null {
  const trimmed = (description ?? '').trim()
  if (trimmed.length === 0) {
    return null
  }
  if (trimmed.length > FIELDSET_DESCRIPTION_MAX_LENGTH) {
    throw new FieldsetDomainError(
      'description',
      `Description must be ${FIELDSET_DESCRIPTION_MAX_LENGTH} characters or fewer.`,
    )
  }
  return trimmed
}

export function createFieldset(props: {
  readonly id: string
  readonly organizationId: string
  readonly name: string
  readonly description: string | null
  readonly displayOrder: number
  readonly nowUtc: Date
  readonly actorUserId: string | null
}): Fieldset {
  if (props.organizationId.trim().length === 0) {
    throw new FieldsetDomainError('organizationId', 'Organization id is required.')
  }
  const name = normalizeName(props.name)
  return {
    id: props.id,
    organizationId: props.organizationId,
    name,
    normalizedName: normalizeFieldName(name),
    description: normalizeDescription(props.description),
    displayOrder: props.displayOrder,
    fields: [],
    ...markCreated(props.nowUtc, props.actorUserId),
  }
}

export function updateFieldset(
  fieldset: Fieldset,
  input: {
    readonly name: string
    readonly description: string | null
    readonly displayOrder: number
  },
  nowUtc: Date,
  actorUserId: string | null,
): Fieldset {
  const name = normalizeName(input.name)
  return markUpdated(
    {
      ...fieldset,
      name,
      normalizedName: normalizeFieldName(name),
      description: normalizeDescription(input.description),
      displayOrder: input.displayOrder,
    },
    nowUtc,
    actorUserId,
  )
}

/** Replaces the members and their order. A field appears at most once; callers validate that each
 * is an active field of the fieldset's organization first. */
export function setFieldsetFields(
  fieldset: Fieldset,
  inputs: readonly FieldsetFieldInput[],
  nowUtc: Date,
  actorUserId: string | null,
): Fieldset {
  const seen = new Set<string>()
  const fields: FieldsetField[] = []
  for (const input of inputs) {
    if (seen.has(input.fieldDefinitionId)) {
      throw new FieldsetDomainError(
        'fieldDefinitionIds',
        `Field '${input.fieldDefinitionId}' is listed more than once.`,
      )
    }
    seen.add(input.fieldDefinitionId)
    fields.push({
      id: input.id,
      fieldsetId: fieldset.id,
      fieldDefinitionId: input.fieldDefinitionId,
      displayOrder: input.displayOrder,
    })
  }
  return markUpdated({ ...fieldset, fields }, nowUtc, actorUserId)
}
