import { randomBytes } from 'node:crypto'
import { type Auditable, markCreated, markUpdated } from '../common/index.js'
import { Role, UserStatus } from '../enums/index.js'
import { normalizeEmail } from './email.js'
import { UserDomainError } from './errors.js'

// Organization-scoped account (SPEC/20-feature-organizations-and-users.md "User Fields",
// SPEC/20-feature-auth.md). `organizationId` is null only for the global Site Admin (auth
// requirement #7). Owns the invariants for lockout (auth requirement #6) and admin-issued
// temporary password expiry (auth requirement #13); login orchestration lives in
// @collega/application/auth.

const MAX_FAILED_ATTEMPTS = 5
const LOCKOUT_WINDOW_MS = 15 * 60 * 1000
const LOCKOUT_DURATION_MS = 15 * 60 * 1000
const TEMPORARY_PASSWORD_VALIDITY_MS = 24 * 60 * 60 * 1000

/** A 25x25 PNG is well under 4 KB; this cap is a safety net against a caller bypassing the
 * resize pipeline, not a functional limit. */
export const USER_MAX_PORTRAIT_BYTES = 64 * 1024

export type User = Auditable & {
  readonly id: string
  readonly organizationId: string | null
  readonly firstName: string
  readonly lastName: string
  readonly email: string
  readonly normalizedEmail: string
  readonly passwordHash: string
  readonly role: Role
  readonly status: UserStatus
  readonly mustChangePassword: boolean
  readonly failedLoginCount: number
  readonly lockoutWindowStartUtc: Date | null
  readonly lockedUntilUtc: Date | null
  /**
   * Set only while an admin-issued temporary password is outstanding and unused. Cleared on
   * first successful login with it, or when the password is subsequently changed. Auth
   * requirement #13: "expire after 24 hours [if unused]".
   */
  readonly temporaryPasswordExpiresAtUtc: Date | null
  /**
   * Optional square profile portrait, stored as a small pre-resized PNG thumbnail. Null when the
   * user has no portrait, in which case callers fall back to the initials avatar. The domain
   * never decodes or resizes image content - that (and the "reject anything that isn't a real
   * GIF/JPEG/PNG" security check) happens in the Application/Infrastructure image pipeline before
   * `setUserPortrait` is called; this only guards the stored size so a malformed caller can't
   * persist an oversized blob.
   */
  readonly portraitPng: Uint8Array | null
  /**
   * Server-side session-revocation stamp (SPEC/20-feature-auth.md #35-36). Embedded in every
   * issued JWT at issuance time; regenerated whenever all of this user's existing sessions must
   * be invalidated (password change, admin-issued temporary password). A JWT whose embedded
   * stamp no longer matches this value is rejected the same way an expired token is - see
   * @collega/application/auth's token authentication service.
   */
  readonly securityStamp: string
}

function requireNonBlank(value: string, field: string, message: string): void {
  if (value.trim().length === 0) {
    throw new UserDomainError(field, message)
  }
}

function generateSecurityStamp(): string {
  return randomBytes(16).toString('hex').toUpperCase()
}

type CreateInternalInput = {
  readonly id: string
  readonly organizationId: string | null
  readonly firstName: string
  readonly lastName: string
  readonly email: string
  readonly passwordHash: string
  readonly role: Role
  readonly status: UserStatus
  readonly mustChangePassword: boolean
}

function createInternal(
  input: CreateInternalInput,
  nowUtc: Date,
  actorUserId: string | null,
): User {
  requireNonBlank(input.firstName, 'firstName', 'First Name is required.')
  requireNonBlank(input.lastName, 'lastName', 'Last Name is required.')
  requireNonBlank(input.email, 'email', 'Email is required.')
  requireNonBlank(input.passwordHash, 'passwordHash', 'Password Hash is required.')

  const trimmedEmail = input.email.trim()

  return {
    id: input.id,
    organizationId: input.organizationId,
    firstName: input.firstName.trim(),
    lastName: input.lastName.trim(),
    email: trimmedEmail,
    normalizedEmail: normalizeEmail(trimmedEmail),
    passwordHash: input.passwordHash,
    role: input.role,
    status: input.status,
    mustChangePassword: input.mustChangePassword,
    failedLoginCount: 0,
    lockoutWindowStartUtc: null,
    lockedUntilUtc: null,
    temporaryPasswordExpiresAtUtc: null,
    portraitPng: null,
    securityStamp: generateSecurityStamp(),
    ...markCreated(nowUtc, actorUserId),
  }
}

export type CreateSiteAdminUserInput = {
  /** Generated by the caller with `crypto.randomUUID()` - the domain never generates one
   * (SPEC/decisions.md 2026-09-06). */
  readonly id: string
  readonly firstName: string
  readonly lastName: string
  readonly email: string
  readonly passwordHash: string
}

/** Seeds the single global platform account (auth requirement #7-9). Always forces a password
 * change on first login. */
export function createSiteAdminUser(input: CreateSiteAdminUserInput, nowUtc: Date): User {
  return createInternal(
    {
      id: input.id,
      organizationId: null,
      firstName: input.firstName,
      lastName: input.lastName,
      email: input.email,
      passwordHash: input.passwordHash,
      role: Role.SiteAdmin,
      status: UserStatus.Active,
      mustChangePassword: true,
    },
    nowUtc,
    null,
  )
}

export type CreateOrganizationUserInput = {
  /** Generated by the caller with `crypto.randomUUID()` - the domain never generates one
   * (SPEC/decisions.md 2026-09-06). */
  readonly id: string
  readonly organizationId: string
  readonly firstName: string
  readonly lastName: string
  readonly email: string
  readonly passwordHash: string
  readonly role: Role
  readonly status: UserStatus
  readonly mustChangePassword: boolean
}

export function createOrganizationUser(
  input: CreateOrganizationUserInput,
  nowUtc: Date,
  actorUserId: string | null = null,
): User {
  if (input.role === Role.SiteAdmin) {
    throw new Error('Organization users cannot be assigned the Site Admin role.')
  }

  return createInternal(
    {
      id: input.id,
      organizationId: input.organizationId,
      firstName: input.firstName,
      lastName: input.lastName,
      email: input.email,
      passwordHash: input.passwordHash,
      role: input.role,
      status: input.status,
      mustChangePassword: input.mustChangePassword,
    },
    nowUtc,
    actorUserId,
  )
}

/** Self-service profile edit (auth requirement #20): first and last name only. Email, role,
 * organization, and status are administrator-controlled and never change here. */
export function updateUserName(
  user: User,
  firstName: string,
  lastName: string,
  nowUtc: Date,
  actorUserId: string | null,
): User {
  requireNonBlank(firstName, 'firstName', 'First Name is required.')
  requireNonBlank(lastName, 'lastName', 'Last Name is required.')

  return markUpdated(
    { ...user, firstName: firstName.trim(), lastName: lastName.trim() },
    nowUtc,
    actorUserId,
  )
}

/** Stores a pre-validated, pre-resized PNG portrait thumbnail on the user record. The bytes must
 * already be a decoded/re-encoded PNG produced by the image pipeline - this only enforces a
 * defensive upper bound on the stored size, not image validity. */
export function setUserPortrait(
  user: User,
  portraitPng: Uint8Array,
  nowUtc: Date,
  actorUserId: string | null,
): User {
  if (portraitPng.length === 0) {
    throw new Error('Portrait content is required.')
  }

  if (portraitPng.length > USER_MAX_PORTRAIT_BYTES) {
    throw new Error(`Portrait exceeds the maximum stored size of ${USER_MAX_PORTRAIT_BYTES} bytes.`)
  }

  return markUpdated({ ...user, portraitPng }, nowUtc, actorUserId)
}

/** Clears the stored portrait so the initials avatar is shown again. */
export function removeUserPortrait(user: User, nowUtc: Date, actorUserId: string | null): User {
  return markUpdated({ ...user, portraitPng: null }, nowUtc, actorUserId)
}

export type AdministerUserInput = {
  readonly firstName: string
  readonly lastName: string
  readonly email: string
  readonly role: Role
  readonly status: UserStatus
}

/**
 * Administrator edit of a user's profile, role, and status (org-and-users "User Rules"). A
 * non-Site-Admin account can never be moved to the Site Admin role. Organization membership is
 * immutable here - a non-Site-Admin user belongs to exactly one organization.
 */
export function administerUser(
  user: User,
  input: AdministerUserInput,
  nowUtc: Date,
  actorUserId: string | null,
): User {
  requireNonBlank(input.firstName, 'firstName', 'First Name is required.')
  requireNonBlank(input.lastName, 'lastName', 'Last Name is required.')
  requireNonBlank(input.email, 'email', 'Email is required.')

  if (user.organizationId !== null && input.role === Role.SiteAdmin) {
    throw new Error('Organization users cannot be assigned the Site Admin role.')
  }

  const trimmedEmail = input.email.trim()

  return markUpdated(
    {
      ...user,
      firstName: input.firstName.trim(),
      lastName: input.lastName.trim(),
      email: trimmedEmail,
      normalizedEmail: normalizeEmail(trimmedEmail),
      role: input.role,
      status: input.status,
    },
    nowUtc,
    actorUserId,
  )
}

export function isUserLockedOut(user: User, nowUtc: Date): boolean {
  return user.lockedUntilUtc !== null && user.lockedUntilUtc.getTime() > nowUtc.getTime()
}

export function isTemporaryPasswordExpired(user: User, nowUtc: Date): boolean {
  return (
    user.temporaryPasswordExpiresAtUtc !== null &&
    user.temporaryPasswordExpiresAtUtc.getTime() <= nowUtc.getTime()
  )
}

/**
 * Auth requirement #6: five failed attempts inside a rolling 15-minute window trigger a
 * 15-minute lockout. Implemented as a window that resets when a failed attempt lands more than
 * 15 minutes after the previous window started (a fixed-window approximation of a true sliding
 * window - see Open Items in the implementation tracker).
 */
export function registerFailedLoginAttempt(user: User, nowUtc: Date): User {
  let lockoutWindowStartUtc: Date
  let failedLoginCount: number

  if (
    user.lockoutWindowStartUtc === null ||
    nowUtc.getTime() - user.lockoutWindowStartUtc.getTime() > LOCKOUT_WINDOW_MS
  ) {
    lockoutWindowStartUtc = nowUtc
    failedLoginCount = 1
  } else {
    lockoutWindowStartUtc = user.lockoutWindowStartUtc
    failedLoginCount = user.failedLoginCount + 1
  }

  const lockedUntilUtc =
    failedLoginCount >= MAX_FAILED_ATTEMPTS
      ? new Date(nowUtc.getTime() + LOCKOUT_DURATION_MS)
      : user.lockedUntilUtc

  return markUpdated(
    { ...user, lockoutWindowStartUtc, failedLoginCount, lockedUntilUtc },
    nowUtc,
    null,
  )
}

/**
 * Clears the failed-attempt/lockout counters after a successful authentication.
 *
 * The temporary-password deadline survives here on purpose. Only a completed rotation
 * (`changeUserPassword`) retires it - clearing it on login instead would turn an unrotated
 * admin-issued temporary password, one the issuing admin still knows, into a permanent
 * credential, which is what auth requirement #13's expiry exists to prevent.
 */
export function registerSuccessfulLogin(user: User, nowUtc: Date): User {
  return markUpdated(
    {
      ...user,
      failedLoginCount: 0,
      lockoutWindowStartUtc: null,
      lockedUntilUtc: null,
      temporaryPasswordExpiresAtUtc: user.mustChangePassword
        ? user.temporaryPasswordExpiresAtUtc
        : null,
    },
    nowUtc,
    user.id,
  )
}

/** Voluntary or forced (first-login) password change. Clears `mustChangePassword` per auth
 * requirement #31. */
export function changeUserPassword(user: User, newPasswordHash: string, nowUtc: Date): User {
  requireNonBlank(newPasswordHash, 'passwordHash', 'Password Hash is required.')

  return markUpdated(
    {
      ...user,
      passwordHash: newPasswordHash,
      mustChangePassword: false,
      temporaryPasswordExpiresAtUtc: null,
      securityStamp: generateSecurityStamp(),
    },
    nowUtc,
    user.id,
  )
}

/**
 * Admin-issued temporary password (auth requirements #12-13). Forces a change on next login and
 * starts the 24-hour unused-expiry window. Also clears any active lockout so the new credential
 * is immediately usable.
 */
export function issueTemporaryPassword(
  user: User,
  temporaryPasswordHash: string,
  nowUtc: Date,
  actorUserId: string,
): User {
  requireNonBlank(temporaryPasswordHash, 'passwordHash', 'Password Hash is required.')

  return markUpdated(
    {
      ...user,
      passwordHash: temporaryPasswordHash,
      mustChangePassword: true,
      temporaryPasswordExpiresAtUtc: new Date(nowUtc.getTime() + TEMPORARY_PASSWORD_VALIDITY_MS),
      failedLoginCount: 0,
      lockoutWindowStartUtc: null,
      lockedUntilUtc: null,
      securityStamp: generateSecurityStamp(),
    },
    nowUtc,
    actorUserId,
  )
}
