/**
 * One person following one idea (SPEC/20-feature-idea-following.md). Following is a read: it
 * grants nothing and changes nothing about the idea. At most one row per person per idea, which
 * the database's `ux_idea_followers_idea_id_user_id` unique index guarantees rather than this type.
 *
 * Shaped like `IdeaUpvote`: `idea_followers` has no `updated_at_utc`/`*_by_user_id` columns.
 */
export type IdeaFollower = {
  readonly id: string
  readonly ideaId: string
  readonly userId: string
  readonly createdAtUtc: Date
}

export type CreateIdeaFollowerProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in. */
  readonly id: string
  readonly ideaId: string
  readonly userId: string
  readonly nowUtc: Date
}

export function createIdeaFollower(props: CreateIdeaFollowerProps): IdeaFollower {
  return { id: props.id, ideaId: props.ideaId, userId: props.userId, createdAtUtc: props.nowUtc }
}
