import { UpvoteDomainError } from './errors.js'

/**
 * A single user's active upvote on an idea (SPEC/20-feature-ideas-and-engagement.md "Upvotes").
 * Upvoting is a toggle: a user has at most one active upvote per idea, enforced by the database's
 * `ux_idea_upvotes_idea_id_user_id` unique index rather than re-checked here, and only the user who
 * cast an upvote can remove it (an Application-layer concern - the lookup is scoped to the caller).
 *
 * Immutable data, not a class - consistent with `packages/domain/src/ideas`. `idea_upvotes` has no
 * `updated_at_utc`/`*_by_user_id` columns, so this predates `Auditable` rather than using it.
 */
export type IdeaUpvote = {
  readonly id: string
  readonly ideaId: string
  readonly userId: string
  readonly createdAtUtc: Date
}

export type CreateIdeaUpvoteProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md). */
  readonly id: string
  readonly ideaId: string
  readonly userId: string
  readonly nowUtc: Date
}

export function createIdeaUpvote(props: CreateIdeaUpvoteProps): IdeaUpvote {
  if (!props.id || props.id.trim().length === 0) {
    throw new UpvoteDomainError('id', 'Upvote id is required.')
  }
  if (!props.ideaId || props.ideaId.trim().length === 0) {
    throw new UpvoteDomainError('ideaId', 'Idea id is required.')
  }
  if (!props.userId || props.userId.trim().length === 0) {
    throw new UpvoteDomainError('userId', 'User id is required.')
  }
  return { id: props.id, ideaId: props.ideaId, userId: props.userId, createdAtUtc: props.nowUtc }
}
