import type { Auditable } from '../common/index.js'
import { markCreated, markUpdated } from '../common/index.js'
import { CommentDomainError } from './errors.js'

export const BODY_MAX_LENGTH = 2000

/**
 * A plain-text comment on an idea (SPEC/20-feature-ideas-and-engagement.md "Comments"). All
 * authenticated users of the idea's organization, including Read Only, can comment. Authors may
 * edit and delete their own comments; in-scope admins may delete any (Application-layer
 * concerns). Comments carry the same email-based mentions as ideas.
 *
 * Immutable data plus the transition functions below, per `packages/domain/src/common` - not a
 * class, matching `packages/domain/src/ideas`. `comment_mentions` rows carry no data beyond the
 * (comment, user) pair, so - as with `Idea.mentionedUserIds` - they are modeled here as a plain
 * id array rather than a separate child entity; Wave C generates each junction row's id at
 * persistence time.
 */
export type Comment = Auditable & {
  readonly id: string
  readonly ideaId: string
  readonly authorUserId: string
  readonly body: string
  readonly mentionedUserIds: readonly string[]
}

export type CreateCommentProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md). */
  readonly id: string
  readonly ideaId: string
  /** The acting user, recorded as author AND as created/updated-by (SPEC/20-feature-view-as.md
   * rule 15 - authorship records the TARGET, never rewritten to the real administrator). */
  readonly authorUserId: string
  readonly body: string
  readonly mentionedUserIds: readonly string[]
  readonly nowUtc: Date
}

function assertRequiredId(field: string, value: string, message: string): string {
  if (!value || value.trim().length === 0) {
    throw new CommentDomainError(field, message)
  }
  return value
}

/**
 * Field name and message text match the .NET request contract
 * (`Collega.API.Contracts.Comments.CreateCommentRequest.Body`, `[RequiredField]` /
 * `[MaxLengthField(2000)]`) rather than the domain's own defensive `ArgumentException` wording -
 * that is where the golden corpus's recorded 400 actually originates (SPEC/decisions.md
 * 2026-09-06 "Wave B conventions"). Required-ness is judged on the trimmed value (matching
 * `RequiredAttribute`'s own trim), length on the raw value (matching `MaxLengthAttribute`, which
 * does not trim first) - the two checks are independent so they never both fire.
 */
function normalizeBody(body: string): string {
  const raw = body ?? ''
  if (raw.trim().length === 0) {
    throw new CommentDomainError('body', 'Body is required.')
  }
  if (raw.length > BODY_MAX_LENGTH) {
    throw new CommentDomainError('body', `Body must be ${BODY_MAX_LENGTH} characters or fewer.`)
  }
  return raw.trim()
}

function normalizeMentions(mentionedUserIds: readonly string[]): readonly string[] {
  return [...new Set(mentionedUserIds.filter((id) => id.length > 0))]
}

export function createComment(props: CreateCommentProps): Comment {
  const ideaId = assertRequiredId('ideaId', props.ideaId, 'Idea id is required.')
  const authorUserId = assertRequiredId(
    'authorUserId',
    props.authorUserId,
    'Author id is required.',
  )
  const body = normalizeBody(props.body)
  const mentionedUserIds = normalizeMentions(props.mentionedUserIds)

  return {
    id: props.id,
    ideaId,
    authorUserId,
    body,
    mentionedUserIds,
    ...markCreated(props.nowUtc, authorUserId),
  }
}

/** Replaces the body and mention set together, matching .NET's `Comment.Edit` (a single
 * combined transition rather than separate ones - unlike Ideas, which needed body/mentions/tags
 * to vary independently). */
export function editComment(
  comment: Comment,
  body: string,
  mentionedUserIds: readonly string[],
  nowUtc: Date,
  actorUserId: string | null,
): Comment {
  return markUpdated(
    {
      ...comment,
      body: normalizeBody(body),
      mentionedUserIds: normalizeMentions(mentionedUserIds),
    },
    nowUtc,
    actorUserId,
  )
}
