// A time-boxed container Issues are pulled into for execution
// (SPEC/20-feature-issues-and-delivery.md "New entity: Sprint"). Org-scoped and soft-deletable,
// like Status, and flat - Slice 2's Outcome groups Issues as a lens and never becomes a parent of
// this.
//
// Immutable data plus transition functions rather than a class, per packages/domain/src/common:
// every mutation already takes an explicit `nowUtc` and `actorUserId`.

import { type Auditable, markCreated, markUpdated } from '../common/index.js'
import { SprintState } from '../enums/index.js'

export const SPRINT_NAME_MAX_LENGTH = 100
export const SPRINT_GOAL_MAX_LENGTH = 500

/** Mirrors `StatusInvariantError` so the Application layer can key a 400 on `field`. */
export class SprintInvariantError extends Error {
  readonly field: string

  constructor(field: string, message: string) {
    super(message)
    this.name = 'SprintInvariantError'
    this.field = field
  }
}

export type Sprint = Auditable & {
  readonly id: string
  readonly organizationId: string
  /** Required. Not unique - "Sprint 12" may legitimately recur across years. */
  readonly name: string
  readonly goal: string | null
  /** `YYYY-MM-DD`, matching `Idea.dueDate` - the repository converts to a `date` column. */
  readonly startDate: string
  readonly endDate: string
  /** Optional. The active-user-in-this-org check belongs to the Application layer. */
  readonly ownerUserId: string | null
  readonly state: SprintState
  readonly isDeleted: boolean
}

function requireText(value: string, label: string, maxLength: number): string {
  const trimmed = value.trim()
  if (trimmed.length === 0) {
    throw new SprintInvariantError(label.toLowerCase(), `${label} is required.`)
  }
  if (trimmed.length > maxLength) {
    throw new SprintInvariantError(
      label.toLowerCase(),
      `${label} must be ${maxLength} characters or fewer.`,
    )
  }
  return trimmed
}

function optionalText(value: string | null, label: string, maxLength: number): string | null {
  if (value === null) {
    return null
  }
  const trimmed = value.trim()
  if (trimmed.length === 0) {
    return null
  }
  if (trimmed.length > maxLength) {
    throw new SprintInvariantError(
      label.toLowerCase(),
      `${label} must be ${maxLength} characters or fewer.`,
    )
  }
  return trimmed
}

/**
 * The `endDate >= startDate` window.
 *
 * The comparison is a plain string compare, which is only correct for zero-padded `YYYY-MM-DD` -
 * hence the shape check first. It is there to make the comparison meaningful, not to second-guess
 * the caller: a malformed date would otherwise compare as if it were a real one and pass.
 */
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

function requireWindow(startDate: string, endDate: string): { start: string; end: string } {
  if (!ISO_DATE.test(startDate)) {
    throw new SprintInvariantError('startDate', 'Start Date must be a calendar date.')
  }
  if (!ISO_DATE.test(endDate)) {
    throw new SprintInvariantError('endDate', 'End Date must be a calendar date.')
  }
  if (endDate < startDate) {
    throw new SprintInvariantError('endDate', 'End Date must be on or after Start Date.')
  }
  return { start: startDate, end: endDate }
}

export function createSprint(params: {
  /** Generated by the Application layer with `crypto.randomUUID()`, as everywhere in this package. */
  readonly id: string
  readonly organizationId: string
  readonly name: string
  readonly goal: string | null
  readonly startDate: string
  readonly endDate: string
  readonly ownerUserId: string | null
  readonly nowUtc: Date
  readonly actorUserId: string | null
}): Sprint {
  if (params.organizationId.trim().length === 0) {
    throw new SprintInvariantError('organizationId', 'Organization id is required.')
  }
  const window = requireWindow(params.startDate, params.endDate)

  return {
    id: params.id,
    organizationId: params.organizationId,
    name: requireText(params.name, 'Name', SPRINT_NAME_MAX_LENGTH),
    goal: optionalText(params.goal, 'Goal', SPRINT_GOAL_MAX_LENGTH),
    startDate: window.start,
    endDate: window.end,
    ownerUserId: params.ownerUserId,
    state: SprintState.Planned,
    isDeleted: false,
    ...markCreated(params.nowUtc, params.actorUserId),
  }
}

/**
 * Renames, re-goals, re-dates and reassigns the owner.
 *
 * The dates of a `Completed` sprint are locked: its window is now a historical record of when the
 * work actually happened, and anything reading back "what shipped in Q3" would silently change
 * answer. Name, goal and owner stay editable there - fixing a typo on a finished sprint rewrites
 * no history.
 */
export function updateSprint(
  sprint: Sprint,
  params: {
    readonly name: string
    readonly goal: string | null
    readonly startDate: string
    readonly endDate: string
    readonly ownerUserId: string | null
  },
  nowUtc: Date,
  actorUserId: string | null,
): Sprint {
  if (sprint.isDeleted) {
    throw new SprintInvariantError('sprint', 'A deleted sprint cannot be updated.')
  }
  const window = requireWindow(params.startDate, params.endDate)
  if (
    sprint.state === SprintState.Completed &&
    (window.start !== sprint.startDate || window.end !== sprint.endDate)
  ) {
    throw new SprintInvariantError('startDate', 'A completed sprint cannot be re-dated.')
  }

  return markUpdated(
    {
      ...sprint,
      name: requireText(params.name, 'Name', SPRINT_NAME_MAX_LENGTH),
      goal: optionalText(params.goal, 'Goal', SPRINT_GOAL_MAX_LENGTH),
      startDate: window.start,
      endDate: window.end,
      ownerUserId: params.ownerUserId,
    },
    nowUtc,
    actorUserId,
  )
}

/**
 * `Planned -> Active`. An explicit action, never derived from `startDate` passing: a sprint the
 * team has not actually picked up is not in progress, whatever the calendar says.
 */
export function startSprint(sprint: Sprint, nowUtc: Date, actorUserId: string | null): Sprint {
  if (sprint.state !== SprintState.Planned) {
    throw new SprintInvariantError('state', 'Only a planned sprint can be started.')
  }
  return markUpdated({ ...sprint, state: SprintState.Active }, nowUtc, actorUserId)
}

/**
 * `Active -> Completed`.
 *
 * Carry-over - returning every Issue whose delivery status is not `Complete` to the backlog - is
 * the Application layer's, because it spans aggregates: this function can see the sprint and
 * nothing else, and an Issue is an `Idea` row it has no reach into. Completion being an explicit
 * action rather than the end date passing is exactly what makes that carry-over deterministic:
 * there is one moment it happens, with an actor attached.
 */
export function completeSprint(sprint: Sprint, nowUtc: Date, actorUserId: string | null): Sprint {
  if (sprint.state !== SprintState.Active) {
    throw new SprintInvariantError('state', 'Only an active sprint can be completed.')
  }
  return markUpdated({ ...sprint, state: SprintState.Completed }, nowUtc, actorUserId)
}

/**
 * Soft-deletes so assigned Issues keep a resolvable reference. Idempotent, like
 * `softDeleteStatus`. Unassigning those Issues to the backlog first is the Application layer's, for
 * the same cross-aggregate reason as carry-over; no Issue is ever deleted with a sprint.
 */
export function softDeleteSprint(sprint: Sprint, nowUtc: Date, actorUserId: string | null): Sprint {
  if (sprint.isDeleted) {
    return sprint
  }
  return markUpdated({ ...sprint, isDeleted: true }, nowUtc, actorUserId)
}
