import type { ImpersonationEndReason } from '../enums/index.js'
import { ImpersonationDomainError } from './errors.js'

// A live "View As" session: a real administrator temporarily acting as another user
// (SPEC/20-feature-view-as.md). Deliberately a persisted server-side row rather than a claim in
// the access token - the token keeps identifying only the real user and is never reissued to
// start or end a session, so a captured token carries no impersonation authority. It is also what
// makes idle expiry, central revocation and non-nestability enforceable at all.
//
// Ending is a soft close (`endedAtUtc`) rather than a delete: the row is the audit record of who
// acted as whom and for how long, and deleting it would destroy exactly the accountability the
// feature exists to provide.
//
// Expressed as an immutable type plus pure transition functions rather than the C# entity class,
// per the Wave B house style (SPEC/decisions.md 2026-09-06) - every transition already takes an
// explicit `nowUtc`, so a class with private setters buys nothing.

/** Idle window (rule 17). No authenticated request for this long ends the session. */
export const IMPERSONATION_IDLE_TIMEOUT_MS = 30 * 60 * 1000

/** Hard cap from start (rule 17), regardless of activity. */
export const IMPERSONATION_ABSOLUTE_LIFETIME_MS = 2 * 60 * 60 * 1000

export type ImpersonationSession = {
  readonly id: string

  /** The administrator who started this - the identity the access token actually names. */
  readonly realUserId: string

  /** The user being acted as. Their identity is what authorization sees (rule 4). */
  readonly targetUserId: string

  readonly startedAtUtc: Date

  /** Advanced on each authenticated request; the basis for idle expiry. */
  readonly lastSeenAtUtc: Date

  /** Fixed at start. Never extended by activity - that is the point of the hard cap. */
  readonly absoluteExpiresAtUtc: Date

  /** Set when the session ends, by exit or by expiry being observed. Null while live. */
  readonly endedAtUtc: Date | null

  /** Why it ended, for the audit trail. Null while live. */
  readonly endReason: ImpersonationEndReason | null
}

export type StartImpersonationSessionInput = {
  /** Generated by the caller with `crypto.randomUUID()` - the domain never generates one
   * (SPEC/decisions.md 2026-09-06). */
  readonly id: string
  readonly realUserId: string
  readonly targetUserId: string
}

export function startImpersonationSession(
  input: StartImpersonationSessionInput,
  nowUtc: Date,
): ImpersonationSession {
  if (!input.realUserId) {
    throw new ImpersonationDomainError('realUserId', 'Real User Id is required.')
  }

  if (!input.targetUserId) {
    throw new ImpersonationDomainError('targetUserId', 'Target User Id is required.')
  }

  // Defence in depth. Authorization refuses this earlier with a 403; the invariant is restated
  // here so the entity cannot represent a nonsensical state regardless of how it is reached.
  if (input.realUserId === input.targetUserId) {
    throw new ImpersonationDomainError('targetUserId', 'A user cannot act as themselves.')
  }

  return {
    id: input.id,
    realUserId: input.realUserId,
    targetUserId: input.targetUserId,
    startedAtUtc: nowUtc,
    lastSeenAtUtc: nowUtc,
    absoluteExpiresAtUtc: new Date(nowUtc.getTime() + IMPERSONATION_ABSOLUTE_LIFETIME_MS),
    endedAtUtc: null,
    endReason: null,
  }
}

/**
 * True when the session has neither been ended nor run past either expiry bound. Evaluated
 * server-side on every request (rule 18) - a client timer may warn, but never decides.
 */
export function isImpersonationSessionActiveAt(
  session: ImpersonationSession,
  nowUtc: Date,
): boolean {
  return (
    session.endedAtUtc === null &&
    nowUtc.getTime() < session.absoluteExpiresAtUtc.getTime() &&
    nowUtc.getTime() - session.lastSeenAtUtc.getTime() < IMPERSONATION_IDLE_TIMEOUT_MS
  )
}

/** Records activity, refreshing the idle window. A no-op once the session is over. */
export function touchImpersonationSession(
  session: ImpersonationSession,
  nowUtc: Date,
): ImpersonationSession {
  if (session.endedAtUtc !== null) {
    return session
  }

  return { ...session, lastSeenAtUtc: nowUtc }
}

/**
 * Closes the session. Idempotent - the first reason wins, so an expiry observed after an
 * explicit exit cannot rewrite why it ended.
 */
export function endImpersonationSession(
  session: ImpersonationSession,
  nowUtc: Date,
  reason: ImpersonationEndReason,
): ImpersonationSession {
  if (session.endedAtUtc !== null) {
    return session
  }

  return { ...session, endedAtUtc: nowUtc, endReason: reason }
}
