import { AiDomainError } from './errors.js'

// One published version of the idea-assist system prompt and its two fixed redirect strings
// (SPEC/20-feature-ai-idea-assist.md rules 34-36).
//
// The first platform-scoped entity in the domain - unlike every other persisted type here, it
// carries no `organizationId`. The prompt is one setting for the whole deployment, exactly like
// the API key (rule 29), not organization content. A future reader should not "fix" the missing
// scope.
//
// Append-only: publishing writes a new row and moves the active pointer; restoring an earlier
// version writes a COPY of it as a new row (rule 36). Nothing here is ever edited in place, which
// is also why - unlike every `Auditable` entity elsewhere in this codebase - this type has no
// `updatedAtUtc`/`updatedByUserId`: nothing ever updates a row after it is written.
//
// What this type does NOT control: the `<organization_data>` block and its escaping are
// assembled in the application layer (see `../../application/ai/prompt-builder.ts`, ported from
// .NET's `Collega.Infrastructure.Ai.IdeaAssistPromptBuilder`). No stored body can reintroduce the
// fence-closing defect the Sprint 7 review found - it CAN delete the prose telling the model to
// distrust that block, which is why publishing offers safety probes (rule 37).

/** Where the server renders the fenced, escaped organization catalog. Required in every body. */
export const ORGANIZATION_CATALOG_PLACEHOLDER = '{{ORGANIZATION_CATALOG}}'

/**
 * Where the server renders the fenced scope statement, or nothing when the organization has
 * none. Required even though it is often empty at render time: a body omitting it would silently
 * disable every organization's scope statement (rule 6) with no error raised anywhere.
 */
export const SCOPE_STATEMENT_PLACEHOLDER = '{{SCOPE_STATEMENT}}'

/**
 * Generous: a working prompt is a couple of thousand characters and operators need room to
 * explain themselves. The real cost control is that this text sits behind the cache breakpoint,
 * so length is paid for once per cache window rather than per turn.
 */
export const AI_PROMPT_BODY_MAX_LENGTH = 20_000

/**
 * Short, matching `ORGANIZATION_AI_SCOPE_STATEMENT_MAX_LENGTH`. These are one-line messages shown
 * in a chat bubble, not documents.
 */
export const AI_PROMPT_REDIRECT_MAX_LENGTH = 500

export type AiPromptVersion = {
  readonly id: string
  /** Monotonic and human-facing - this is what the UI and the audit event name. */
  readonly version: number
  readonly body: string
  readonly outOfScopeRedirect: string
  readonly conversationClosedRedirect: string
  /**
   * Exactly one row is active at a time, or none - in which case the built-in default compiled
   * into the product is used. "No rows" is therefore the normal initial state, and resetting to
   * the default is deactivating all rather than inserting anything.
   */
  readonly isActive: boolean
  readonly createdAtUtc: Date
  readonly createdByUserId: string | null
}

export type PublishAiPromptVersionProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` and passed in - domain does
   * not generate ids (SPEC/decisions.md 2026-09-06). */
  readonly id: string
  /** Supplied by the caller, which owns the sequence because only it can see the existing rows. */
  readonly version: number
  readonly body: string
  readonly outOfScopeRedirect: string
  readonly conversationClosedRedirect: string
  readonly nowUtc: Date
  readonly actorUserId: string | null
}

function requireWithinLength(
  field: string,
  value: string,
  requiredMessage: string,
  maxLength: number,
  maxLengthMessage: string,
): void {
  if (value.length === 0) {
    throw new AiDomainError(field, requiredMessage)
  }
  if (value.length > maxLength) {
    throw new AiDomainError(field, maxLengthMessage)
  }
}

/**
 * Publishes a new version. Throws `AiDomainError` when a field is empty, over length, or the
 * body is missing a required placeholder.
 */
export function publishAiPromptVersion(props: PublishAiPromptVersionProps): AiPromptVersion {
  const body = (props.body ?? '').trim()
  const outOfScopeRedirect = (props.outOfScopeRedirect ?? '').trim()
  const conversationClosedRedirect = (props.conversationClosedRedirect ?? '').trim()

  requireWithinLength(
    'body',
    body,
    'The prompt body is required.',
    AI_PROMPT_BODY_MAX_LENGTH,
    `The prompt body cannot exceed ${AI_PROMPT_BODY_MAX_LENGTH} characters.`,
  )

  // Checked here rather than only at the API edge: this is the invariant that keeps the catalog
  // and the scope statement reachable at all, so it must hold for every path that writes a row.
  if (!body.includes(ORGANIZATION_CATALOG_PLACEHOLDER)) {
    throw new AiDomainError(
      'body',
      `The prompt body must contain ${ORGANIZATION_CATALOG_PLACEHOLDER}, which is where the ` +
        "organization's idea types and business impacts are rendered. Without it the assistant " +
        'has no catalog to classify against.',
    )
  }

  if (!body.includes(SCOPE_STATEMENT_PLACEHOLDER)) {
    throw new AiDomainError(
      'body',
      `The prompt body must contain ${SCOPE_STATEMENT_PLACEHOLDER}. Without it, every ` +
        "organization's scope statement would be silently ignored.",
    )
  }

  requireWithinLength(
    'outOfScopeRedirect',
    outOfScopeRedirect,
    'The out-of-scope redirect is required.',
    AI_PROMPT_REDIRECT_MAX_LENGTH,
    `The out-of-scope redirect cannot exceed ${AI_PROMPT_REDIRECT_MAX_LENGTH} characters.`,
  )

  requireWithinLength(
    'conversationClosedRedirect',
    conversationClosedRedirect,
    'The conversation-closed redirect is required.',
    AI_PROMPT_REDIRECT_MAX_LENGTH,
    `The conversation-closed redirect cannot exceed ${AI_PROMPT_REDIRECT_MAX_LENGTH} characters.`,
  )

  return {
    id: props.id,
    version: props.version,
    body,
    outOfScopeRedirect,
    conversationClosedRedirect,
    isActive: true,
    createdAtUtc: props.nowUtc,
    createdByUserId: props.actorUserId,
  }
}

/**
 * Stands this version down. Called on the previously active row when a new one is published, and
 * on every row when resetting to the built-in default.
 */
export function deactivateAiPromptVersion(version: AiPromptVersion): AiPromptVersion {
  return { ...version, isActive: false }
}
