import { type AiCallOutcome, AiKeySource } from '../enums/index.js'
import { AiDomainError } from './errors.js'

// One model call's token consumption, attributed to the organization whose work it was
// (SPEC/20-feature-ai-idea-assist.md rule 28c).
//
// A METER, deliberately separate from the audit event rule 27 also writes for every call. The
// audit event is the accountability trail - prose plus metadata, written once and read rarely.
// This table is aggregated on the hot path: the daily budget gate sums the current UTC day
// before EVERY call, and the usage surface groups by organization. Neither should be parsing
// JSON out of audit rows. Both records are written; neither is derived from the other.
//
// Carries no prompt and no transcript text (rule 28e), the same constraint rule 27 places on the
// audit log.

export type AiUsageRecord = {
  readonly id: string
  /**
   * The organization the spend belongs to. REQUIRED - unlike an audit event's organizationId,
   * which is nullable because platform-level actions have no org. Every model call is made on
   * behalf of exactly one organization, and an unattributed row would be spend nobody can be
   * billed for.
   */
  readonly organizationId: string
  /**
   * Who really made the call. While a View As session is live this stays the REAL
   * administrator, mirroring an audit event's actor.
   */
  readonly actorUserId: string | null
  /** The impersonated user when the call went through View As; null otherwise. */
  readonly onBehalfOfUserId: string | null
  readonly boardId: string | null
  readonly occurredAtUtc: Date
  /**
   * The model id actually used. Stored rather than assumed so a later model change - the id is
   * configuration - cannot retroactively mislabel historical consumption.
   */
  readonly model: string
  readonly inputTokens: number
  readonly outputTokens: number
  readonly cacheReadInputTokens: number
  readonly cacheCreationInputTokens: number
  /**
   * The per-million rates in effect when the call was made. Stored on the row rather than
   * looked up at read time because this data supports cost pass-through: re-pricing history
   * when configuration changes would silently restate what an organization owes.
   */
  readonly inputRatePerMillion: number
  readonly outputRatePerMillion: number
  /**
   * Which credential paid for the call. Always `Platform` in v1 - per-org keys are deferred
   * (rule 30). The column exists now so that when they land, each org's own key can be metered
   * separately with no backfill.
   */
  readonly keySource: AiKeySource
  /**
   * How the call ended. Refused and failed turns are recorded too: they consumed tokens, and a
   * meter that counted only successes would not bound spend.
   */
  readonly outcome: AiCallOutcome
}

export type CreateAiUsageRecordProps = {
  /** Generated by the Application layer with `crypto.randomUUID()` - domain does not generate
   * ids (SPEC/decisions.md 2026-09-06). */
  readonly id: string
  readonly organizationId: string
  readonly model: string
  readonly occurredAtUtc: Date
  readonly inputTokens: number
  readonly outputTokens: number
  readonly inputRatePerMillion: number
  readonly outputRatePerMillion: number
  readonly outcome: AiCallOutcome
  readonly actorUserId?: string | null
  readonly onBehalfOfUserId?: string | null
  readonly boardId?: string | null
  readonly cacheReadInputTokens?: number
  readonly cacheCreationInputTokens?: number
  readonly keySource?: AiKeySource
}

function requireNonNegative(field: string, value: number): number {
  // A provider that reports a negative count is broken; letting it through would corrupt the
  // budget total in the direction of under-counting, which is the dangerous direction.
  if (value < 0) {
    throw new AiDomainError(field, 'Token counts cannot be negative.')
  }
  return value
}

export function createAiUsageRecord(props: CreateAiUsageRecordProps): AiUsageRecord {
  if (!props.organizationId) {
    throw new AiDomainError('organizationId', 'Usage must be attributed to an organization.')
  }
  if (!props.model || props.model.trim().length === 0) {
    throw new AiDomainError('model', 'Model is required.')
  }

  return {
    id: props.id,
    organizationId: props.organizationId,
    actorUserId: props.actorUserId ?? null,
    onBehalfOfUserId: props.onBehalfOfUserId ?? null,
    boardId: props.boardId ?? null,
    occurredAtUtc: props.occurredAtUtc,
    model: props.model.trim(),
    inputTokens: requireNonNegative('inputTokens', props.inputTokens),
    outputTokens: requireNonNegative('outputTokens', props.outputTokens),
    cacheReadInputTokens: requireNonNegative(
      'cacheReadInputTokens',
      props.cacheReadInputTokens ?? 0,
    ),
    cacheCreationInputTokens: requireNonNegative(
      'cacheCreationInputTokens',
      props.cacheCreationInputTokens ?? 0,
    ),
    inputRatePerMillion: props.inputRatePerMillion,
    outputRatePerMillion: props.outputRatePerMillion,
    keySource: props.keySource ?? AiKeySource.Platform,
    outcome: props.outcome,
  }
}

/** Total tokens billed for this call - what the daily budget gate (rule 28a) is measured in. */
export function totalTokensOf(record: AiUsageRecord): number {
  return (
    record.inputTokens +
    record.outputTokens +
    record.cacheReadInputTokens +
    record.cacheCreationInputTokens
  )
}

/**
 * Cost in USD from the rates stored on this row. Cache reads and cache writes are priced off the
 * input rate at the provider's published multipliers - 0.1x for a read, 1.25x for a write.
 */
export function estimatedCostOf(record: AiUsageRecord): number {
  const perMillion = 1_000_000
  const input = (record.inputTokens * record.inputRatePerMillion) / perMillion
  const cacheRead = (record.cacheReadInputTokens * record.inputRatePerMillion * 0.1) / perMillion
  const cacheWrite =
    (record.cacheCreationInputTokens * record.inputRatePerMillion * 1.25) / perMillion
  const output = (record.outputTokens * record.outputRatePerMillion) / perMillion
  return input + cacheRead + cacheWrite + output
}
