import Link from 'next/link'
import { RegisterForm } from '@/components/auth/register-form'
import { AuthPitch } from '@/components/auth-pitch'

export const metadata = { title: 'Create your account · Collega' }

/**
 * Create an account from an invite code (comp Q `s-register`).
 *
 * **The code is not accepted from the query string, and that is a decision rather than an oversight.**
 * A `/register?code=…` link is the more convenient handout, but the code is a standing, non-expiring
 * credential that self-registers anyone into the organization (`tools/golden/README.md`), and a URL
 * is the one place a secret is copied without anybody choosing to copy it: browser and shell
 * history, the platform's request logs, a `Referer`, and every screenshot of the address bar. It
 * would also outlive the tester — the link keeps working, and keeps being forwardable, long after
 * they are in. So the operator sends the link and the code as two things, the code is pasted once
 * into a field that echoes it back on a failed attempt, and nothing durable records it on the way.
 *
 * Nothing is fetched, so this stays a Server Component with the form as the only client boundary.
 */
export default function RegisterPage() {
  return (
    <>
      <AuthPitch
        heading="Your invite code is your organization."
        points={[
          'One email per account, across every organization',
          'A code can be regenerated by your admin at any time',
        ]}
      >
        <p>
          There is no organization picker. The code your administrator gave you decides where your
          account lives, and it lands you in that organization as a member.
        </p>
      </AuthPitch>

      <div className="flex flex-col justify-center bg-background px-6 py-16 sm:px-14">
        <div className="mx-auto w-full max-w-[356px]">
          <h1>Create your account</h1>
          <p className="mt-1 mb-5 text-base text-muted-foreground">
            Enter the invite code from your organization admin. It decides which organization you
            join.
          </p>

          <RegisterForm />

          <p className="mt-4 text-sm text-muted-foreground">
            Already have an account? <Link href="/login">Sign in</Link>.
          </p>
        </div>
      </div>
    </>
  )
}
